# Generated by Django 5.2.6 on 2025-09-07 07:17

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        VectorExtension(),
    ]
