# Generated by Django 5.2.6 on 2025-09-07 07:22

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("archiv", "0001_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="The collection's title",
                        max_length=250,
                        verbose_name="Titel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="TextSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "text_id",
                    models.CharField(
                        help_text="Some unique ID for the text",
                        max_length=250,
                        verbose_name="Text ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The actual text content", verbose_name="Content"
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1536,
                        null=True,
                        verbose_name="Embedding (text-embedding-3-small)",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snippets",
                        to="archiv.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Text Snippet",
                "verbose_name_plural": "Text Snippets",
                "ordering": ["text_id"],
                "unique_together": {("collection", "text_id")},
            },
        ),
    ]
