# Generated by Django 5.2.6 on 2025-09-08 11:18

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='textsnippet',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='textsnippetindex', opclasses=['vector_l2_ops']),
        ),
    ]
