# Generated by Django 5.2.6 on 2026-02-19 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0003_textsnippet_textsnippetindex"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="textsnippet",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Text Snippet",
                "verbose_name_plural": "Text Snippets",
            },
        ),
    ]
