# Generated by Django 5.2.6 on 2026-02-20 08:06

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0004_alter_textsnippet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsnippet',
            name='embedding_nomic',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True, verbose_name='Embedding (nomic-embed-text-v1.5)'),
        ),
        migrations.AddIndex(
            model_name='textsnippet',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding_nomic'], m=16, name='textsnippetindex_nomic', opclasses=['vector_l2_ops']),
        ),
    ]
